### ISSUE TITLE
different colors

### ISSUE THREAD

**Issue by ghost** [tomysshadow/Shockwave-3D-World-Converter#10]
Hi

Could you please try model "1943" here

https://www.mameworld.info/3darcade/

I don't know if it's a bug but the model has different colors (black vs dark grey) for the sides:

Black side:

![afbeelding](https://user-images.githubusercontent.com/122493908/213880660-b077b6cb-3693-4004-8e78-83cae3650f11.png)

Dark grey side:

![afbeelding](https://user-images.githubusercontent.com/122493908/213880677-93b79d1c-aaae-4079-96c7-37a61ca00a48.png)

In the MTL I can also see the different colors

newmtl 1943sideleftin
Ka 0.007843 0.007843 0.007843
Kd 0.000000 0.000000 0.000000
Ks 0.086275 0.086275 0.086275
Ns 12.800000
d 1.000000
newmtl 1943tmoldleft
Ka 0.011765 0.011765 0.011765
Kd 0.007843 0.007843 0.007843
Ks 0.627451 0.627451 0.627451
Ns 12.799999
d 1.000000
newmtl 1943siderightin
Ka 0.000000 0.000000 0.000000
Kd 0.011765 0.011765 0.011765
Ks 0.086275 0.086275 0.086275
Ns 12.800000
d 1.000000
newmtl 1943tmoldright
Ka 0.000000 0.000000 0.000000
Kd 0.000000 0.000000 0.000000
Ks 0.627451 0.627451 0.627451
Ns 12.800000
d 1.000000

If you want to have a look? Does the original W3D has these colors too or is it a small bug?

**Comment by tomysshadow** [comment]
Have you looked in your model viewer where the 1943sideleftin, 1943tmoldleft, etc. materials actually are? They're along the bottom/inside of the cabinet, not the outside like shown in the screenshots. The shaders are different in the original world, although a difference of 0.01 or less from black to white is barely perceptible and was probably a mistake by the original creator.

The outside, on the other hand, is one uniform colour. It uses the 1943black material. You can easily see this by changing 1943black to a brighter colour. The difference in colour that is seen in your screenshots is due to the position of the lighting in your scene, not a difference of materials in the model.

P.S. if you want an easier way to preview Shockwave 3D Worlds in their original format you may want the [Shockwave 3D Viewer](https://www.adobe.com/support/director/downloads.html) (scroll down to the Shockwave category.) Please avoid posting issues about conversion when you don't know if the original world was meant to look that way.

**Comment by ghost** [comment]
I also noticed this on other models. Mostly black vs. dark grey and it seems this issue returns with those same colors.
I didn't find a working Director version so I can't view the original W3D file.
Do you know a viewer that can display W3D files maybe?

**Comment by ghost** [comment]
Hi

Yes, I now saw this but ... I have no lights since the mode I'm using in Blender is the material view which has no lights used.
So then this is still a mystery. Why are both sides not black?

This must be a Blender bug the since:

- both sides need to be black
- the W3D has this too
- i'm not in Blender mode that uses lights

Or what I need to do?

**Comment by tomysshadow** [comment]
In Blender the world has its own default light even without lamps present, as without it everything would be pitch black and difficult to gauge. See: https://www.reddit.com/r/blender/comments/gkelr9/is_it_possible_to_turn_off_default_camera_light/

In fact, you can see the lighting change as you rotate the camera around by holding middle click, even with a plain white cube.

**Comment by ghost** [comment]
Wow! You just have to know all this...
I never heard of it. 
This seems to be only in 'material preview' mode, what I used too :D

There is also a 'render' mode and there everything is black (both sides of the model).
Do you think there is no light in 'render' mode?

**Comment by tomysshadow** [comment]
There are several reasons a render may appear to have light, even if no lamps are present, such as the ones provided by this [Stack Exchange answer.](https://blender.stackexchange.com/questions/74867/no-lights-in-scene-still-lighting-up)

> Objects may appear illuminated, if ...
> 
> 
> - they are illuminated by [lamp](https://docs.blender.org/manual/en/dev/render/cycles/lamps.html#lamps) objects
> - they are illuminated by mesh lights with [emission](https://docs.blender.org/manual/en/dev/render/cycles/nodes/types/shaders/emission.html#emission-node) shaders
> - they are emitting light completely or partially, if they have an emission shader
> - the wrongheaded use of an Add Shader in a material
> - they are illuminated by the [world](https://docs.blender.org/manual/en/dev/render/cycles/world.html#surface) ([background](https://docs.blender.org/manual/en/dev/render/cycles/nodes/types/shaders/background.html#background-node) shader)
> - [ambient occlusion](https://docs.blender.org/manual/en/dev/render/cycles/world_settings.html#ambient-occlusion) is activated

**Comment by ghost** [comment]
Do you use Blender yourself or is this just the same for each 3D program?
I feel very stupid now 😭

**Comment by tomysshadow** [comment]
I haven't used Blender a great deal but have encountered the issue of lighting falsely affecting the perception of colour before in other 3D modeling tools and am aware that this is something that can happen in general.

**Comment by ghost** [comment]
Ok! Thanks a lot for the help.
You hopefully understand now why I thought it was a bug in your program. I had no idea of all these things ☺️

Does Director do this too?

**Comment by ghost** [comment]
Can I maybe have your email to ask questions when I find something weird again? (General things)
I tried on blender forums but nobody seems to know anything. It are more like artists there but they don't know technical things.
I recently found the collada importer in Blender is completely broken! (Wrong colors, missing textures and sometimes even parts of the model not present)

I reported it as a bug.

**Comment by tomysshadow** [comment]
In Shockwave 3D, a light is added to the scene by default. If the default light is deleted, the scene is pitch black and nothing can be seen. The default light does change the perception of colour (although it looks a bit more subtle to my eyes than Blender's default Studio Light.)

I'm on Twitter @TOMYSSHADOW if you need. However be aware I haven't used Blender for any actual 3D modeling before, so I can't really provide help outside of general stuff with it. I used to create my own 3D models, but it's been several years since then. I liked using a (now ancient) modeling tool called 3DVIA Shape - it was kind of similar to Sketchup but created by Dassault Systemes - and I kind of lost interest in modeling when it was discontinued. I still do programming stuff, though! ;)

**Comment by ghost** [comment]
Do you maybe know where to disable the light they are talking about?

https://www.reddit.com/r/blender/comments/gkelr9/is_it_possible_to_turn_off_default_camera_light/

In "system" nothing is there. 

There is "lights" but nothing there too

![afbeelding](https://user-images.githubusercontent.com/122493908/213932045-263d4992-bade-49a2-ad60-fa3df296c7a5.png)

Blender is nice but the documentation is not up to date :(

**Comment by tomysshadow** [comment]
Seems to have moved to Preferences > Lights > Studio Lights > Editor. There
are checkboxes you can tick and customize the settings.

**Comment by ghost** [comment]
If nothing is checked, there is still this light.
So I think it can't be disabled

**Comment by ghost** [comment]
I have the answer!

https://developer.blender.org/T104058
