### ISSUE TITLE
Command line or ShortCut Keys

### ISSUE THREAD

**Issue by Sembiance** [tomysshadow/Shockwave-3D-World-Converter#13]
Is it possible to get a command line flag to automatically start extraction?
I see that I can pass the file to read as the first argument and that works, but it would be awesome if I could pass for the second arg 'c:\out\out.obj' and have it auto extract to there.

The reason why I'm doing this is I'm attempting to automate the use of this program in order to process thousands of W3D files and I'm having trouble getting the 'Export Wavefront' button to click. My virtual mouse clicks don't seem to be working on it, like it's not a real button or something. I can send the 'tab' keystroke twice to tab over to the button, and then pressing 'space' causes the button to animate like it was clicked, but sadly no export window ever pops up.
Alternatively to the second command line argument, if it would respond to a Ctrl-S or Ctrl-E or some other shortcut to activate the Export window, that would be awesome!

**Comment by tomysshadow** [comment]
The fact is, I've been meaning to overhaul this tool for some time now, and just haven't had time. There's a lot of things that I want to add to it:
-support for exporting worlds straight from a Director Movie (DIR/DXR/DCR)
-writing an Xtra wrapper around the Autodesk FBX SDK to allow for FBX output (proper texture layers)
-some kind of support for multiselect/batch processing
-just generally improving the code, which is kind of disorganized
etc.

Unfortunately, it just isn't the top of my priority list right now and is going to have to wait, a few months at the minimum. I only just recently published my [ExportFile Xtra](https://github.com/tomysshadow/ExportFile-Xtra) for Director last week, which took a long time so I would like a break from programming for a while. And when I do come back to it, I already had an idea for the next thing I wanted to work on (which is also semi-Director related,) and _after_ that I was thinking of returning to this.

In the meantime, as a temporary fix - very hacky, but you could add this line to the startMovie event in the Start script (which will trigger on any keypress)
`set the keyDownScript to "mouseUp(script(" & QUOTE & "Export Wavefront Object Button" & QUOTE & "))"`

**Comment by Sembiance** [comment]
> In the meantime, as a temporary fix - very hacky, but you could add this line to the startMovie event in the Start script (which will trigger on any keypress) `set the keyDownScript to "mouseUp(script(" & QUOTE & "Export Wavefront Object Button" & QUOTE & "))"`

I am currently just executing the .exe version. Is adding the code you mentioned to a startup script something that can work with the exe version? Or do I need to track down the XTras you mention and create a director project and use the .dir version? If the latter, do you have any tips as to which macromedia director version to use?

I truly appreciate that you’ve created this though, as I’m not aware of any other .w3d converters.

I totally get that you are looking to take a break from programming. But if you were able to find time to add the second argument to auto export for the .exe version, I’d be willing to send over some money to help cover your time. Maybe $500 or more if needed.

By the way this isn’t being used in anything commercial, it’s being used to convert these files into a format folks can more easily consume to help preserve our valuable digital history.

**Comment by tomysshadow** [comment]
I can't accept monetary donations, as much as I appreciate the offer - it would qualify my software as commercial software under the new Cyber Resilience Act, which would subject me to regulations that I don't want to be beholden to. But fine, I guess, if it's really worth that much to you I'll put out a patch that just adds hotkeys. It's another layer of duct tape on top of a bunch of layers of duct tape already, I really want to give this thing its long overdue rewrite, but if it's really urgent then I will do it. I'll put out a patch update for it (let's call it 1.3.9.1.)

I don't want to add the second command line argument as an output destination, at least not in that form, because if I do ever add multiselect/batch processing, I want to allow multiple input files to be specified over the command line as well, so making the second argument the output destination would not allow me to do that. So I would need to put some design thought into the best way I could accept multiple files via command line and still specify destinations for them.

There does exist one other Shockwave 3D World converter that I am aware of, [SOLA G1.](http://www.eee-craft.com/sola_g1/index.html) This is a freeware (though closed source) utility, created by the Japanese company EEE-Craft, and it converts to KML (Google Earth's 3D model format.) However, it doesn't support textures at all, so it only outputs plain white model files (the later versions of SOLA remove the ability to convert with Shockwave 3D as input, only accepting it as an output format.) This was the impetus for me to create my own converter. Funnily, I also use the free [awaSW3D Xtra](http://www.eee-craft.com/director/awaSW3D/) (by the same developer) in order to export the textures!

As per the README, the version of Director required to edit this is 11.5, if you did ever want to look at how it works.

**Comment by tomysshadow** [comment]
Alright, I made a commit - it's really jank, so not going to make it into an actual release, for now - that adds hotkeys. For now, I'm not going to put any more effort into it, since I'm really trying to force myself to have a break right now in spite of the favours people are asking me. Anyway, here are the hotkeys:
-Ctrl+B: Browse
-Ctrl+E: Export Wavefront OBJ
-Ctrl+C: Cancel
-F1 - F12: Toggle Features

**Comment by Sembiance** [comment]
Thanks for the hotkeys, it's appreciated.
