### ISSUE TITLE
JPG/PNG textures

### ISSUE THREAD

**Issue by ghost** [tomysshadow/Shockwave-3D-World-Converter#5]
Hi

Is there a way you could make JPG/PNG textures instead of TIFF textures or are the TIFF textures the original format used inside the W3D model?
So basically: will texture quality increase when using another format then TIFF?

**Comment by tomysshadow** [comment]
TIFF is used as an export format for two reasons:

1. Because it is the image format used by the awaSW3D Xtra, which is used to export the textures:
http://www.eee-craft.com/director/awaSW3D/

2. Because it allows the export of texture layers, even though Wavefront OBJ itself does not support it.

> So basically: will texture quality increase when using another format then TIFF?

No: TIFF is a lossless format, so the image quality is already the best possible.

**Comment by tomysshadow** [comment]
Closing this issue because this feature will not be added.
